import type { Metadata } from "next";
import { Dancing_Script,Archivo_Black } from "next/font/google";
import "./globals.css";
const ArchivoBlack=Archivo_Black({
  subsets:['latin'],
  display:'swap',
  weight:'400'
})
const DancingScript=Dancing_Script({
subsets:['latin'],
display:'swap'
})

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // className={`${DancingScript.className}`}
        className={`${ArchivoBlack.className}`}
      >
        {children}
      </body>
    </html>
  );
}
